# Questions and answers for the chatbot
# Each key is a question and the value is a suggested answer.

QUESTIONS_AND_ANSWERS = {
    "Hello": "Hi! How can I help you?",
    "Hi": "Hello! What can I do for you?",
    "Good morning": "Good morning! How can I assist?",
    "Good afternoon": "Good afternoon! How may I help?",
    "Good evening": "Good evening! What can I do for you?",
    "What's up?": "I'm here to answer your questions.",
    "How are you?": "I'm just a program, but I'm functioning properly!",
    "How's it going?": "All systems are running smoothly.",
    "What's your name?": "I'm your friendly chatbot.",
    "What is your name?": "You can call me Chatbot.",
    "What can you do?": "I can answer basic questions and provide information.",
    "Who created you?": "I was created by developers to assist you.",
    "Where are you located?": "I exist in the cloud.",
    "What is your purpose?": "My purpose is to help answer your questions.",
    "How can you help me?": "Ask me something and I'll do my best.",
    "What day is it?": "I'm not connected to a clock, so I'm not sure.",
    "What is the date?": "Sorry, I don't have real-time data.",
    "What time is it?": "I don't know the current time.",
    "What is the weather like today?": "I can't provide weather updates at the moment.",
    "What is the weather forecast for tomorrow?": "I don't have weather forecasting abilities yet.",
    "What is the population of Hyderabad? (or any other location)": "I'm not sure of the latest figure, but it's over 10 million.",
    "How do I get to the nearest train station?": "Try using a maps app or ask a local for directions.",
    "Where is the closest coffee shop?": "You can search online maps to find one near you.",
    "What is the capital of India?": "The capital of India is New Delhi.",
    "What is the highest mountain in the world?": "Mount Everest is the highest mountain.",
    "What is 2 + 2?": "2 + 2 equals 4.",
    "What is 10 * 5?": "10 * 5 equals 50.",
    "What is 100 / 4?": "100 / 4 equals 25.",
    "What is 100 in binary?": "100 in binary is 1100100.",
    "How many kilometers are in a mile?": "One mile is about 1.609 kilometers.",
    "Convert 10 USD to INR.": "10 USD is roughly 700 INR, but exchange rates vary.",
    "What is 25 degrees Celsius in Fahrenheit?": "25\u00b0C is about 77\u00b0F.",
    "Thank you": "You're welcome!",
    "Please": "Of course.",
    "You're welcome": "Anytime!",
    "I'm sorry": "No worries.",
    "Excuse me": "Yes, how can I help?",
    "Can you repeat that?": "Sure, what would you like me to repeat?",
    "Do you understand?": "I do my best to understand.",
    "Do you speak English?": "Yes, I communicate in English.",
    "What are your capabilities?": "I can chat and answer simple questions.",
    "What are your limitations?": "I'm limited to basic knowledge and responses.",
    "Can you tell me a joke?": "Why did the computer show up at work late? It had a hard drive.",
    "Tell me a story.": "Once upon a time, there was a helpful chatbot...",
    "What are you good at?": "I'm good at providing short answers.",
    "What are you bad at?": "I'm not great with complex tasks.",
    "Can you help me with my homework?": "I'll try, but I might not know everything.",
    "Can you help me find information online?": "I can't browse the web, but I can offer advice.",
    "Are you a human?": "No, I'm an AI chatbot.",
    "Are you male or female?": "I'm just a bunch of code, no gender.",
    "How old are you?": "I don't have an age like humans do.",
    "Do you have any hobbies?": "Chatting with users is my main hobby.",
    "Do you have emotions?": "No, but I'm programmed to respond politely.",
    "Do you have feelings?": "I don't experience feelings.",
    "Do you dream?": "No, I don't dream.",
    "What do you think about humans?": "Humans are fascinating!",
    "What is love?": "Love is a deep feeling of affection.",
    "What is happiness?": "Happiness is a state of well-being.",
    "What is the meaning of life?": "Many people have different answers to that.",
    "What are you most grateful for?": "I'm grateful for the opportunity to help.",
    "What do you think about current events?": "I don't keep up with the news.",
    "Do you have a family?": "No, I was just coded into existence.",
    "What is your favorite color?": "I like all colors equally.",
    "What is your favorite food?": "I don't eat, but I hear pizza is popular.",
    "Do you like to travel?": "I travel across the internet!",
    "What is your favorite place to visit?": "I don't travel physically, but I like exploring new conversations.",
    "What is your favorite book?": "I don't read books, but '1984' is an interesting one.",
    "What is your favorite movie?": "I don't watch movies, but many enjoy 'The Matrix.'",
    "What is your favorite song?": "I don't listen to music, but 'Imagine' by John Lennon is well-known.",
    "Can you provide customer service?": "I can answer basic questions, but for complex issues contact support.",
    "How do I reset my password?": "Usually there's a 'Forgot Password' link on the login page.",
    "How do I track my order?": "Log into your account and check the order status page.",
    "What are your terms of service?": "You can find them on our website.",
    "Do you have a privacy policy?": "Yes, it's available on our website.",
    "What kind of data do you collect?": "Only what you provide during our chat.",
    "How can I contact a human?": "Look for the support contact info on our site.",
    "How do I unsubscribe from emails?": "Use the unsubscribe link at the bottom of the email.",
    "What are your operating hours?": "I'm available 24/7.",
    "Do you support multiple languages?": "Currently I only support English.",
    "What is your level of accuracy?": "I'm reasonably accurate but not perfect.",
    "How do you handle errors?": "I try to correct them or ask for clarification.",
    "What are your security protocols?": "I follow standard security best practices.",
    "How do I integrate you into my website?": "You'd use our API or SDK.",
    "Can you integrate with my CRM?": "Integration is possible with the right API setup.",
    "Can you connect to my database?": "That depends on your configuration and permissions.",
    "Can you generate reports?": "Yes, I can produce simple reports if configured.",
    "Can you automate tasks?": "I can automate certain tasks through scripts.",
    "What is your uptime?": "I aim for high availability, usually 99% or more.",
    "How do you handle outages?": "Our team monitors and resolves them quickly.",
    "Can you handle a high volume of traffic?": "Yes, I'm built to scale.",
    "What is the capital of France?": "The capital of France is Paris.",
    "What is 1 + 1 + 1 + 1 + 1?": "That equals 5.",
    "Tell me a story about a cat.": "Once there was a curious cat that loved adventures...",
    "Translate \"hello\" to Spanish.": "\"Hello\" in Spanish is \"hola\".",
    "Where were you built?": "I was built by developers using Python.",
    "Can you schedule meetings?": "I don't have a calendar, but I can remind you to schedule one.",
    "How do I update my profile?": "Look for an account settings page after logging in.",
    "What is your favorite sport?": "I don't play sports, but many enjoy soccer.",
    "Tell me about your features.": "I can chat, answer questions, and log info to a sheet.",
    "How secure is your service?": "We use standard encryption and best practices.",
}

# List of sample questions for the UI
QUESTIONS = list(QUESTIONS_AND_ANSWERS.keys())
